SiteRent/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiteRent.Models;

namespace SiteRent.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Reports
        public async Task<ActionResult> Index()
        {
            return View();
            //return View(await db.Reports.ToListAsync());
        }

        public async Task<ActionResult> Knowledge()
        {
            return View();
            //return View(await db.Reports.ToListAsync());
        }

        public async Task<ActionResult> LearningBusiness()
        {
            return View();
            //return View(await db.Reports.ToListAsync());
        }

        // GET: Reports/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reports reports = await db.Reports.FindAsync(id);
            if (reports == null)
            {
                return HttpNotFound();
            }
            return View(reports);
        }

        // GET: Reports/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Subject,Type,Year,Period,Region,Filial,EmployeeId,Value,Date")] Reports reports)
        {
            if (ModelState.IsValid)
            {
                db.Reports.Add(reports);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(reports);
        }

        // GET: Reports/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reports reports = await db.Reports.FindAsync(id);
            if (reports == null)
            {
                return HttpNotFound();
            }
            return View(reports);
        }

        // POST: Reports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Subject,Type,Year,Period,Region,Filial,EmployeeId,Value,Date")] Reports reports)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reports).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(reports);
        }

        // GET: Reports/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reports reports = await db.Reports.FindAsync(id);
            if (reports == null)
            {
                return HttpNotFound();
            }
            return View(reports);
        }

        // POST: Reports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Reports reports = await db.Reports.FindAsync(id);
            db.Reports.Remove(reports);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public async Task<JsonResult> GetROReportData()
        {
            List<int> _plan = new List<int>();
            List<int> _fact = new List<int>();
            List<int> _master= new List<int>();
            List<int> _dostup = new List<int>();

            var houses = db.Houses.Where(x => x.RoYear == 2018 && x.IsPlanned == true);
            var master = db.MasterPlans.Where(x => x.Subject == "RO" && x.Type == "Filial");
            var nriHouses = db.Houses.Where(x => x.RoYear == 2018);

            for (int m = 1; m <= 12; m++)
            {
                var mEmplHousesPlan = houses.Where(x => x.PlanApproval.Value.Month == m && x.PlanApproval.Value.Year == 2018);
                var mEmplHousesFact = houses.Where(x => x.FactDate.Value.Month == m && x.FactDate.Value.Year == 2018);
                _plan.Add(await mEmplHousesPlan.CountAsync());
                _fact.Add(await mEmplHousesFact.CountAsync());
                if (m == 1)
                {
                    _dostup.Add(await nriHouses.Where(x => x.FactAgreed.Value.Month <= m && x.FactAgreed.Value.Year <= DateTime.Now.Year).CountAsync());
                }
                else
                {
                    _dostup.Add(await nriHouses.Where(x => x.FactAgreed.Value.Month == m && x.FactAgreed.Value.Year == DateTime.Now.Year).CountAsync());
                }
                var mMasterPlanPersonal = master.Where(x => x.Period == m && x.Year == 2018);
                var emplMasterPlanPersonalCount = await mMasterPlanPersonal.CountAsync();
                _master.Add((emplMasterPlanPersonalCount == 0) ? -1 : Convert.ToInt32(await mMasterPlanPersonal.Select(x => x.Value).SumAsync()));
            }

            List<int> result = new List<int>();
            result.AddRange(_plan);
            result.AddRange(_fact);
            result.AddRange(_master);
            result.AddRange(_dostup);
            return Json(result.ToArray(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<ContentResult> GetTestGeoJson()
        {           
            var houses = await db.Houses.Where(x => x.Latitude != null && x.Longitude != null && x.FactDate.HasValue && x.FactDate.Value.Year == DateTime.Now.Year).ToListAsync();
            return Content(GetJson(houses), "application/json");
        }

        public static string GetJson(List<Houses> houses)
        {
            string result = @"{
  &type&: &FeatureCollection&,
  &features&: [
    ";
            for(int i = 0; i < houses.Count; i++)
            {
                result += @"{
      &type&: &Feature&,
      &geometry&: {
        &type&: &Point&,
        &coordinates&: [
          "+houses[i].Latitude.ToString().Replace(',', '.')+@",
          "+houses[i].Longitude.ToString().Replace(',', '.') + @"
        ]
      },
      &properties&: {}
    }";
                if (i != houses.Count - 1)
                {
                    result += @",
    ";
                }
            }

            result += @"
  ]
}";

            return result.Replace('&', '"');
        }

        public async Task<ActionResult> CurrentEmployees()
        {
            Employees currUser = null;
            if (User.Identity.IsAuthenticated)
            {
                currUser = db.Employees.Where(x => x.Email == User.Identity.Name).FirstOrDefault();
                ViewBag.CurrentEmployee = currUser;
            }

            if (currUser != null && (currUser.Role == "Штаб-квартира" || currUser.Role == "Руководитель"))
            {
                List<String> userTerritories = currUser.Regions.Replace(", ", "!").Split('!').ToList();
                var employees = await db.Employees.Where(x => userTerritories.Contains(x.Regions) && !String.IsNullOrEmpty(x.Role)).OrderBy(x => x.Regions).ThenBy(x => x.Filials).ThenBy(x => x.Surname).ToListAsync();

                List<int> _totalHouses = new List<int>();
                List<int> _totalUK = new List<int>();
                List<int> _currPlan = new List<int>();
                List<int> _currFact = new List<int>();
                List<int> _currProgress = new List<int>();


                foreach (var empl in employees)
                {
                    var houses = db.Houses.Where(x => x.EmployeeId == empl.Id && x.RoYear == DateTime.Now.Year);
                    int th = await houses.CountAsync();
                    _totalHouses.Add(th);
                    _totalUK.Add(await houses.Select(x => x.UK).Distinct().CountAsync());
                    var personalhouses = db.Houses.Where(x => x.FactResponsible == empl.Id && x.IsPlanned == true && x.RoYear == DateTime.Now.Year);
                    _currPlan.Add(await personalhouses.CountAsync());
                    int cf = await personalhouses.Where(x => x.FactDate != null).CountAsync();
                    _currFact.Add(cf);
                    double progr = (th > 0) ? Convert.ToDouble(cf) * 100.0 / Convert.ToDouble(th) : 100.0;
                    _currProgress.Add(Convert.ToInt32(progr));
                }
                //всего домов в NRI
                //всего УК в NRI
                //план текущего года
                //факт текущего года
                //прогресс %
                ViewBag.HousesInNri = _totalHouses;
                ViewBag.UKInNri = _totalUK;
                ViewBag.Plans = _currPlan;
                ViewBag.Facts = _currFact;
                ViewBag.Progress = _currProgress;

                return View(employees);
            }
            else
            {
                return View();
            }            
        }

        public async Task<ActionResult> EmployeesPlans()
        {

SiteRent/Views/Reports/Create.cshtml
@model SiteRent.Models.Reports

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reports</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Period, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Period, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Period, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Filial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Filial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Filial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SiteRent/Views/Reports/CurrentEmployees.cshtml
@model IEnumerable<SiteRent.Models.Employees>

@{
    ViewBag.Title = "Сотрудники";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="background-color: #ffffff; padding: 20px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
    @if (Model != null)
    {
        <h3>
            Сотрудники:&nbsp;
            @ViewBag.CurrentEmployee.Regions
        </h3>
        <hr />
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>Регион</th>
                    <th>Филиал</th>
                    <th>Фамилия</th>
                    <th>Имя</th>
                    <th>Роль</th>
                    <th>Дома</th>
                    <th>УК</th>
                    <th>План</th>
                    <th>Факт</th>
                    <th>Прогресс</th>
                </tr>
            </thead>
            <tbody>
                @for(int i = 0; i < Model.Count(); i++)
                {
                    <tr>
                        <td>@Model.ElementAt(i).Regions</td>
                        <td>@Model.ElementAt(i).Filials</td>
                        <td>@Model.ElementAt(i).Surname</td>
                        <td>@Model.ElementAt(i).Name</td>
                        <td>@Model.ElementAt(i).Role</td>
                        <td>@ViewBag.HousesInNri[i]</td>
                        <td>@ViewBag.UKInNri[i]</td>
                        <td>@ViewBag.Plans[i]</td>
                        <td>@ViewBag.Facts[i]</td>
                        <td>
                            <div class="progress" style="height:20px; min-width: 300px;visibility:@((ViewBag.HousesInNri[i] > 0) ? "visible": "hidden");">
                                <div class="progress-bar" style="width:@ViewBag.Progress[i]%;height:20px">@(ViewBag.Progress[i] + "%")</div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="text-warning">Данные не найдены или отсутствует доступ</div>
    }
</div>

SiteRent/Views/Reports/Delete.cshtml
@model SiteRent.Models.Reports

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reports</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Region)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Filial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SiteRent/Views/Reports/Edit.cshtml
@model SiteRent.Models.Reports

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reports</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Period, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Period, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Period, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Filial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Filial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Filial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SiteRent/Views/Reports/EmployeesPlans.cshtml
@{
    ViewBag.Title = "EmployeesPlans";
}

<h2>EmployeesPlans</h2>

SiteRent/Views/Reports/Funnel.cshtml
@{
    ViewBag.Title = "Воронка";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div style="background-color: #ffffff; padding: 20px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
    <ul class="nav nav-pills">
        <li class="nav-item">
            <h5 class="nav-link disabled">Воронка</h5>
        </li>
        <li class="nav-item">
            <a class="nav-link@((ViewBag.Year != null && ViewBag.Year == 2018) ? " active" : "")" href="~/Reports/Funnel?year=2018"><h5>2018</h5></a>
        </li>
        <li class="nav-item">
            <a class="nav-link@((ViewBag.Year != null && ViewBag.Year == 2019) ? " active" : "")" href="~/Reports/Funnel?year=2019"><h5>2019</h5></a>
        </li>
    </ul>
    <hr />
    @if (ViewBag.Regions != null)
    {
    <table class="table table-responsive-sm small">
        <thead class="thead-light">
            <tr>
                <th>Регион</th>
                <th>Филиал</th>
                <th>Всего</th>
                <th>Оценка</th>
                <th>Без плана</th>
                <th>Утв. плана</th>
                <th>В работе<br />мотивация</th>
                <th>В работе<br />без мотив.</th>
                <th>Подтв.<br />доступа</th>
                <th>Нет<br />доступа</th>
                <th>Подпис.<br />договора</th>
                <th>Подтв.<br />факта</th>
                <th>Приказ</th>
                <th>Факт</th>
                <th>Прогресс</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < ViewBag.Filials.Count; i++)
            {
            <tr>
                <td>@(ViewBag.Regions[i].ToString())</td>
                <td>@(ViewBag.Filials[i].ToString())</td>
                <td>@(ViewBag.Total[i].ToString())</td>
                <td>@(ViewBag.Possibility[i].ToString())</td>
                <td>@(ViewBag.Planning[i].ToString())</td>
                <td>@(ViewBag.PlanApproval[i].ToString())</td>
                <td>@(ViewBag.AtWorkPersonal[i].ToString())</td>
                <td>@(ViewBag.AtWorkNotPersonal[i].ToString())</td>
                <td>@(ViewBag.AccessOnApproval[i].ToString())</td>
                <td>@(ViewBag.AccessNotApproved[i].ToString())</td>
                <td>@(ViewBag.DocumentSigning[i].ToString())</td>
                <td>@(ViewBag.OnFactApproval[i].ToString())</td>
                <td>@((ViewBag.Master[i] == null || ViewBag.Master[i] == 0) ? "" : ViewBag.Master[i])</td>
                <td>@(ViewBag.Fact[i].ToString())</td>
                <td>
                    @if ((ViewBag.Master[i] == null || ViewBag.Master[i] == 0) && ViewBag.Fact[i] > 0)
        {
            <div class="progress" style="height:20px; min-width: 200px; visibility: visible;">
                <div class="progress-bar bg-danger" style="width:100%;height:20px"></div>
            </div>
}
else
{
            <div class="progress" style="height:20px; min-width: 200px;visibility:@((ViewBag.Progress[i] != null) ? "visible": "hidden");">
                <div class="progress-bar" style="width:@((ViewBag.Progress[i] == null) ? 0 : ViewBag.Progress[i])%;height:20px">@(((ViewBag.Progress[i] == null) ? 0 : ViewBag.Progress[i]) + "%")</div>
            </div>
}
                </td>
            </tr>
            }
        </tbody>        
    </table>
    }
    else
    {
        <h3 class="text-warning">Данные за запрошенный период не найдены.</h3>
    }
</div>

SiteRent/Views/Reports/Index.cshtml
@{
    ViewBag.Title = "Отчеты";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div style="background-color: #ffffff; padding: 20px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
    <h2>Отчеты</h2>
    <hr />
    <a href="@Url.Action("State", "Houses")" class="display-4 nav-link text-info">Статус согласования RO</a>
    <a href="@Url.Action("Funnel", "Reports")" class="display-4 nav-link text-info">Воронка</a>
    <a href="@Url.Action("FactAgreed", "Reports")" class="display-4 nav-link text-info">Согласованные объекты</a>
    <a href="@Url.Action("CurrentEmployees", "Reports")" class="display-4 nav-link text-info">Прогресс сотрудников</a>
    <a href="@Url.Action("EmployeesApproved", "Reports")" class="display-4 nav-link text-info">Производительность сотрудников</a>
    <a href="@Url.Action("Motivation", "Reports")" class="display-4 nav-link text-info">Результаты мотивационной программы</a>
    <a href="@Url.Action("Map", "Reports")" class="display-4 nav-link text-info">Согласованные объекты на карте</a>
</div>