SiteRent/Controllers/HousesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiteRent.Models;

namespace SiteRent.Controllers
{
    [Authorize]
    public class HousesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Houses
        public async Task<ActionResult> Index()
        {
            int page = 1;
            int year = DateTime.Now.Year;
            int status = 0;
            int plan = 0;
            int fact = 0;
            string search = Request["search"];
            int searchchanged = 0;
            string region = Request["region"];
            string filial = Request["filial"];
            string uk = Request["uk"];
            int employee = 0;

            Employees currUser = null;
            List<String> cuRegions = new List<string>();
            List<String> cuFilials = new List<string>();            

            var houses = db.Houses.Include(h => h.Employee);

            if (User.Identity.IsAuthenticated)
            {
                currUser = db.Employees.Where(x => x.Email == User.Identity.Name).FirstOrDefault();                
            }
            if (currUser != null)
            {
                ViewBag.CurrentEmployee = currUser;
                cuRegions = currUser.Regions.Replace(", ", "!").Split('!').ToList();
                cuFilials = currUser.Filials.Replace(", ", "!").Split('!').ToList();                
            }

            var UserViewEmployees = await db.Employees.Where(e => cuRegions.Contains(e.Regions) && (e.Role == "Переговорщик" || e.Role == "Сопровождающий")).Select(e => new { EmployeeId = e.Id, EmployeeText = e.Surname + " " + e.Name.Substring(0, 1) + ". " + e.Patronymic.Substring(0, 1) + ". (" + e.Role.Substring(0, 1) + ")" }).OrderBy(e => e.EmployeeText).ToListAsync();
            ViewBag.UserViewEmployees = UserViewEmployees;

            if (currUser != null && (currUser.Role == "Руководитель" || currUser.Role == "Ассистент"))
            {
                houses = houses.Where(x => cuFilials.Contains(x.Filial));
            }

            if (currUser != null && (currUser.Role == "Переговорщик" || currUser.Role == "Сопровождающий"))
            {
                houses = houses.Where(x => x.Employee.Email == User.Identity.Name);
            }

            //ViewBag.TotalHouses = houses.Count();

            if (!String.IsNullOrEmpty(Request["page"]) && int.TryParse(Request["page"], out page))
            {

            }
            else
            {
                page = 1;
            }

            if (!String.IsNullOrEmpty(Request["year"]) && int.TryParse(Request["year"], out year) && year >= 2015)
            {

            }
            else
            {
                year = DateTime.Now.Year;
            }

            if (!String.IsNullOrEmpty(Request["status"]) && int.TryParse(Request["status"], out status))
            {

            }
            else
            {
                status = 0;
            }

            if (!String.IsNullOrEmpty(Request["plan"]) && int.TryParse(Request["plan"], out plan))
            {

            }
            else
            {
                plan = 0;
            }

            if (!String.IsNullOrEmpty(Request["fact"]) && int.TryParse(Request["fact"], out fact))
            {

            }
            else
            {
                fact = 0;
            }

            if (!String.IsNullOrEmpty(Request["searchchanged"]) && Request["searchchanged"] == "1")
            {
                page = 1;
            }

            if (!String.IsNullOrEmpty(Request["employee"]) && int.TryParse(Request["employee"], out employee) && employee >= -1)
            {

            }
            else
            {
                employee = 0;
            }

            if (currUser != null && currUser.Role == "Штаб-квартира" && !String.IsNullOrEmpty(region) && cuRegions.IndexOf(region) > -1 && (String.IsNullOrEmpty(filial) || cuFilials.IndexOf(filial) == -1))
            {
                houses = houses.Where(x => x.Region == region);
            }

            if (currUser != null && (currUser.Role == "Руководитель" || currUser.Role == "Штаб-квартира") && !String.IsNullOrEmpty(filial) && cuFilials.IndexOf(filial) > -1)
            {
                houses = houses.Where(x => x.Filial == filial);
            }

            if (currUser != null && (currUser.Role == "Руководитель" || currUser.Role == "Штаб-квартира") && employee != 0)
            {
                if (UserViewEmployees.Where(e => e.EmployeeId == employee).Count() > 0)
                {
                    houses = houses.Where(x => x.EmployeeId == employee);
                }
                else
                {
                    if (employee == -1)
                    {
                        List<int> uve = UserViewEmployees.Select(e => e.EmployeeId).ToList();
                        houses = houses.Where(x => !uve.Contains(x.EmployeeId.Value));
                    }
                }
            }

            if (year >= 2015)
            {
                houses = houses.Where(x => x.RoYear == year);
            }

            switch (status)
            {
                case 0: break;
                case 1: houses = houses.Where(x => x.Status == "Проверка возможности договора с УК"); break;
                case 2: houses = houses.Where(x => x.Status == "Согласование с УК"); break;
                case 3: houses = houses.Where(x => x.Status == "Не согласован с УК"); break;
                case 4: houses = houses.Where(x => x.Status == "Проверка доступа на дом"
                || x.Status == "Нет доступа на объект"
                || x.Status == "Проведение ПИР"
                || x.Status == "Ждем согласование ПИР с проектировщиками ШК"
                || x.Status == "Доработка ПИР"
                || x.Status == "Передача ПИР в УК"
                || x.Status == "Ждем согласования ПИР от УК"
                || x.Status == "ПИР не согласован с УК"
                || x.Status == "Передача дома в СМР"
                || x.Status == "Проведение СМР"
                || x.Status == "Ждем возобновления СМР"
                || x.Status == "Подварка"
                || x.Status == "Приемка работ"
                || x.Status == "Устранение замечаний"
                || x.Status == "Подготовка документов на активацию"
                || x.Status == "На активации"
                || x.Status == "Активирован"); break;
                default: break;
            }

            switch (plan)
            {
                case 0: break;
                case 1: houses = houses.Where(x => x.IsPlanned == true); break;
                case 2: houses = houses.Where(x => x.PlanApproval != null && x.IsPlanned == false); break;
                case 3: houses = houses.Where(x => x.PlanApproval == null && x.FactTransferredToAgreement != null); break;
                default: break;
            }

            switch (fact)
            {
                case 0: break;
                case 1: houses = houses.Where(x => x.IsApproved == true); break;
                case 2: houses = houses.Where(x => x.IsApproved == false && x.FactAgreed != null && x.FactApproved != null && x.FactDocumentDate != null && !String.IsNullOrEmpty(x.FactDocumentLink) && !String.IsNullOrEmpty(x.FactDocumentDescription)); break;
                case 3: houses = houses.Where(x => x.IsPlanned == true && x.IsApproved == false && x.FactAgreed == null); break;
                case 4: houses = houses.Where(x => x.IsPlanned == true && x.IsApproved == false && x.FactApproved == null); break;
                case 5: houses = houses.Where(x => x.IsPlanned == true && x.IsApproved == false && (x.FactDocumentDate == null || String.IsNullOrEmpty(x.FactDocumentLink) || String.IsNullOrEmpty(x.FactDocumentDescription))); break;
                default: break;
            }

            if (!String.IsNullOrEmpty(search))
            {
                houses = houses.Where(x => x.StreetName.Contains(search) || x.City.Contains(search) || x.Area.Contains(search) || x.Status.Contains(search) || x.Number1.Contains(search) || x.GFK.Contains(search) || x.ERP.Contains(search) || x.UK.Contains(search));
            }

            if(houses != null)
            {
                ViewBag.TotalCount = houses.Count();
            }
            else
            {
                ViewBag.TotalCount = 0;
            }

            houses = houses.OrderByDescending(x => x.Id).Skip(15 * (page - 1)).Take(15);

            ViewBag.page = page;

            return View(await houses.ToListAsync());
        }

        // GET: Houses
        public async Task<ActionResult> State()
        {
            //var houses = db.Houses.Include(h => h.Employee);
            //return View(await houses.ToListAsync());

            var houses = db.Houses.Where(x => x.RoYear == 2018);

            List<String> RegionNamesList = new List<string>();
            List<int> RegionPlansList = new List<int>();

            RegionNamesList.Add("Большая Москва");
            RegionNamesList.Add("Юг");
            RegionNamesList.Add("Центр");
            RegionNamesList.Add("Запад");
            RegionNamesList.Add("Восток");

            foreach (string reg in RegionNamesList)
            {
                var mPLl = db.MasterPlans.Where(x => x.Subject == "RO" && x.Type == "Filial" && x.Region == reg && x.Period <= DateTime.Now.Month && x.Year == DateTime.Now.Year).Select(x => x.Value);
                if (await mPLl.CountAsync() > 0)
                {
                    RegionPlansList.Add(Convert.ToInt32(await mPLl.SumAsync()));
                }
                else
                {
                    RegionPlansList.Add(0);
                }
            }

            /*List<int> TotalRegionHouses = new List<int>();

SiteRent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap-largegrid.min.css")
    @Scripts.Render("~/bundles/modernizr")
    <!--<link rel="stylesheet" href="~/Content/sidebar.css"> navbar navbar-expand-lg navbar-light bg-light-->
</head>
<body style="min-height: 75rem; padding-top: 4.5rem;">
    @{SiteRent.Models.Employees LoggedIdEmployee = SiteRent.Models.ApplicationDbContext.Create().Employees.Where(x => x.Email == User.Identity.Name).FirstOrDefault(); }
    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #1a1a1d">
        @Html.ActionLink("SITERENT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Houses")" class="nav-link">
                        <img src="~/Content/Images/sidebar_houses.svg" title="Дома" alt="Дома" style="width: 16px; height: 16px;" />
                        <span>ДОМА</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Planning", "Reports")" class="nav-link">
                        <img src="~/Content/Images/sidebar_cloud.svg" title="Планирование" alt="Планирование" style="width: 16px; height: 16px;" />
                        <span>ПЛАНИРОВАНИЕ</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Reports")" class="nav-link">
                        <img src="~/Content/Images/sidebar_chart.svg" title="Отчеты" alt="Отчеты" style="width: 16px; height: 16px;" />
                        <span>ОТЧЕТНОСТЬ</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Map", "Reports")" class="nav-link">
                        <img src="~/Content/Images/sidebar_placeholder.svg" title="Карта" alt="Карта" style="width: 16px; height: 16px;" />
                        <span>КАРТА</span>
                    </a>
                </li>
                @if (LoggedIdEmployee != null && (LoggedIdEmployee.Role == "Штаб-квартира" || LoggedIdEmployee.Role == "Руководитель"))
                {
                    <li class="nav-item">
                        <a href="@Url.Action("CurrentEmployees", "Reports")" class="nav-link">
                            <img src="~/Content/Images/sidebar_people.png" title="Сотрудники" alt="Сотрудники" style="width: 16px; height: 16px;" />
                            <span>СОТРУДНИКИ</span>
                        </a>
                    </li>
                }
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="@Url.Action("Knowledge", "Reports")" id="dropdown10" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="~/Content/Images/books.svg" title="Знания" alt="Знания" style="width: 16px; height: 16px;" />
                        <span>ЗНАНИЯ</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdown10">
                        <a class="dropdown-item" href="@Url.Action("Knowledge", "Reports")">Каталог</a>
                        <a class="dropdown-item" href="@Url.Action("Knowledge", "Reports")">Банк знаний</a>
                        <a class="dropdown-item" href="@Url.Action("Knowledge", "Reports")">Обучение</a>
                    </div>
                </li>
            </ul>
            @if (User.Identity.IsAuthenticated)
            {
                <ul class="navbar-nav">
                    @Html.Partial("_LoginPartial", (SiteRent.Models.Employees)LoggedIdEmployee)
                </ul>
            }
        </div>
    </nav>

    <main role="main" class="container" id="content">
        @RenderBody()
    </main>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>